# Generated by Django 5.0.6 on 2024-11-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
