# Generated by Django 5.0.6 on 2024-11-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='templateimage',
            name='image',
            field=models.ImageField(default=1, upload_to='template_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
